# Global Configuration
experiment_tracking_status: true

# Data Configuration
data:
  raw_data_path: "../../../data/raw_data/baq_dataset.csv"

# Model Configuration
model:
  model_type: "random_forest" # Options: "random_forest", "xgboost", "lstm"
  random_forest:
    model_params:
      n_estimators: 50
      max_depth: 10
    training_params:
      learning_rate: 0.001
      batch_size: 32
      epochs: 100
  xgboost:
    model_params:
      n_estimators: 50
      max_depth: 10
    training_params:
      learning_rate: 0.001
      batch_size: 32
      epochs: 100
  lstm:
    model_params:
      n_layers: 2
      hidden_size: 128
      dropout: 0.2
    training_params:
      sequence_length: 24
      learning_rate: 0.001
      batch_size: 32
      epochs: 100
      early_stopping_patience: 10
      reduce_lr_patience: 5


# Artifacts Configuration
artifacts:
  base_path: "./artifacts"
  model:
    path: "models"
    filename: "best_model.pkl"
  processors:
    path: "processors"
    filename: "processor.joblib"
  metrics:
    path: "metrics"
    filename: "metrics.json"
  plots:
    path: "plots"
  reports:
    path: "reports"
    filename: "monitoring_report.html"


# Training Configuration
training:
  forecast_horizon: 24
  target_column: "pm2_5_(μg/m³)"
  n_splits: 5
  test_size: 0.2
  random_state: 42

wandb:
  project: "pm25-forecasting"
  entity: null  # Set your wandb username/team
  tags: ["pm2.5", "forecasting", "air-quality"]
  log_model: true
  register_model: false
