# Data Configuration
data:
  dataset: "iris"
  data_path: "data/raw_data/Iris.csv"
  features:
    - SepalLengthCm # Float
    - SepalWidthCm # Float
    - PetalLengthCm # Float
    - PetalWidthCm # Float
  target: "Species" # String
  split:
    train_size: 0.8
    test_size: 0.2
    random_state: 42
    stratify: true

# Processing Configuration
processing:
  data_path: "data/processed_data/Iris.csv"
  scaling:
    method: "standard"  # Options: standard, minmax, robust
    with_mean: true
    with_std: true
  missing_values: "mean"  # Options: mean, median, most_frequent
  feature_engineering:
    polynomial_features:
      enable: false
      degree: 2
    pca:
      enable: false
      n_components: 2

# Model Configuration
model:
  type: "random_forest"  # Options: random_forest, svm, logistic_regression
  hyperparameters:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      bootstrap: true
    svm:
      C: 1.0
      kernel: "rbf"
      gamma: "scale"
    logistic_regression:
      C: 1.0
      penalty: "l2"
      solver: "lbfgs"
      max_iter: 100
      multi_class: "auto"

# Training Configuration
training:
  cross_validation:
    enable: true
    n_splits: 5
    shuffle: true
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  early_stopping:
    enable: false
    patience: 5
    min_delta: 0.001

# MLOps Configuration
mlops:
  experiment_tracking:
    tool: "mlflow"
    tracking_uri: "http://localhost:5000"
  model_registry:
    enable: true
    registry_uri: "sqlite:///mlflow.db"
  hyperparameter_tuning:
    enable: false
    method: "grid"  # Options: grid, random, bayesian
    n_trials: 10
    cv: 3

# Artifacts Configuration
artifacts:
  base_path: "artifacts"
  model:
    path: "models"
    filename: "iris_model.pkl"
  scaler:
    path: "scalers"
    filename: "scaler.pkl"
  metrics:
    path: "metrics"
    filename: "metrics.json"
  plots:
    path: "plots"
    confusion_matrix: "confusion_matrix.png"
    roc_curve: "roc_curve.png"
    feature_importance: "feature_importance.png"
    precision_recall_curve: "precision_recall_curve.png"
  reports:
    path: "reports"
    classification_report: "classification_report.json"
    model_card: "model_card.md"
  versioning:
    enable: true
    naming_pattern: "{model_type}_{timestamp}"
    keep_previous: 5


