name: Model Registry Report

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'PR number to comment on (for manual runs)'
        required: false
        type: number

jobs:
  get-registry-models:
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/registry_report')) || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract issue number
        id: params
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "issue_number=${{ github.event.inputs.issue_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.31"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install project dependencies
        run: uv sync --all-extras

      - name: Run registry report script
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_MODEL_REGISTRY_COLLECTION_PATH: ${{ secrets.WANDB_MODEL_REGISTRY_COLLECTION_PATH }}
        run: uv run src/baq/action_files/get_registry_models.py

      - name: Debug - Show generated report
        run: |
          echo "Generated report content:"
          cat model_registry_report.md || echo "Report file not found."
          ls -la *.md

      - name: Comment on PR
        if: steps.params.outputs.issue_number != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ steps.params.outputs.issue_number }}
          body-file: model_registry_report.md
