name: Get WandB Runs
on:
  issue_comment:

jobs:
  get-runs:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/wandb_list_model')
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest SHA for the PR that was commented on
        id: chatops
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/wandb_list_model"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Runs Using SHA
        uses: machine-learning-apps/wandb-action@master
        with:
          PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
          FILTER_GITHUB_SHA: ${{ steps.chatops.outputs.SHA }}
          BASELINE_TAGS: "['baseline', 'reference']"
          DISPLAY_METRICS: "['accuracy', 'loss', 'best_val_acc', 'best_val_loss', '_runtime']"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          DEBUG: 'true'