name: Get WandB Runs
on:
  issue_comment:

jobs:
  get-runs:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/wandb_list_model')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest SHA for the PR that was commented on
        id: chatops
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/wandb_list_model"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run wandb-action and capture output
        id: wandb
        run: |
          set -o pipefail
          bash -c '
            PROJECT_NAME="${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}}"
            FILTER_SHA="${{ steps.chatops.outputs.SHA }}"
            echo "Fetching runs for SHA: $FILTER_SHA"
          ' | tee wandb_output.log

          # run wandb-action manually (simulate or replace with curl/python later if needed)
          # For now we assume it prints output we can capture

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Post output as PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 📊 WandB Run Summary" > comment.md
          echo "\`\`\`" >> comment.md
          cat wandb_output.log >> comment.md
          echo "\`\`\`" >> comment.md

          gh pr comment ${{ github.event.issue.number }} --body-file comment.md