name: ML Workflow
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.31"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-extras 
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
      - name: Train
        run: uv run src/baq/run.py
    #   - name: Evaluation
    #     env:
    #       REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: | 
    #       echo "## Model Metrics" > report.md
    #       cat metrics.txt >> report.md
            
    #       echo '## Confusion Matrix Plot' >> report.md
    #       echo '![Confusion Matrix](model_results.png)' >> report.md

    #       cml comment create report.md