name: Check Code Quality
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:
  
permissions: write-all

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: iterative/setup-cml@v2
      #   env:
      #     REPO_TOKEN: ${{ secrets.GH_TOKEN }}
      # # Setup DVC and pull data
      # - uses: iterative/setup-dvc@v1
      # - name: Pull data with DVC
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: dvc pull
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.31"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      # Setup and install the project
      - name: Install the project
        run: uv sync --all-extras 
